apiVersion: v2
name: ba-braze-connector
description: A Helm chart for Elementor nodejs apps
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: elementor-chart-library
    version: 3.0.0
    #repository: https://elementor.github.io/devops-library-chart
    repository: file://../../../../DevOps/devops-library-chart/elementor-chart-library/
